### ISSUE TITLE
"Dependency Injection" Çevirisi

### ISSUE THREAD

**Issue by hkulekci** [hkulekci/php-the-right-way#16]
http://kulekci.net/php-the-right-way/#dependency_injection bölümününçevirisi yapılacak.

**Comment by umutphp** [comment]
Hala yardım gerekiyor mu?

**Comment by hkulekci** [comment]
Gerekmez mi :) küçük de olsa bir destek çok güzel olur. Ben baya bir zamandır vakit bulamıyorum. Yeni bir bölüm daha eklenmiş bugün vakit olursa ingilizce hali ile karşılaştırıp hızlıca yeni eklenen değişen bölümleri bir yerde toplayım belki de iş listesini de güncellemek gerekir.

**Comment by umutphp** [comment]
Ben birkaç hafta müsaitim. Bana yetki ver repo'nda :). Bazı taskları ben yapayım.

**Comment by hkulekci** [comment]
Davet gönderdim.
