### ISSUE TITLE
Veritabanları Bölümü Çevirisi Güncellemesi

### ISSUE THREAD

**Issue by hkulekci** [hkulekci/php-the-right-way#17]
https://github.com/hkulekci/php-the-right-way/blob/gh-pages/_posts/07-01-01-Databases.md sayfasında eski çeviri ile yeni hali birlikte duruyor. Son halinin çevirisi kalacak şekilde güncellenecek. Son hali şu anda ingilizce halde olan kısımdır.

**Comment by umutphp** [comment]
@hkulekci İngilizce bir bölüm yok. Bu iş hala açık mi?

**Comment by hkulekci** [comment]
Bu bölüm eskiden `pages/` altındaydı. Son update'den sonra oradan kaldırılmış direk `_posts` altına taşınmış. Kapatabiliriz.

**Comment by umutphp** [comment]
Kapattım o zaman.
