### ISSUE TITLE
"Templating" bölümü çevirisi

### ISSUE THREAD

**Issue by hkulekci** [hkulekci/php-the-right-way#18]
http://kulekci.net/php-the-right-way/#templating bölümünün çevirisi yapılacak.

**Comment by umutphp** [comment]
Template "Arayüz kalıbı" diye çevirebiliriz diye düşünüyorum. Kalıp da denebilir. 

@hkulekci Sence ?

**Comment by hkulekci** [comment]
Arayüz Kalıbı daha doğru sanırım.

**Comment by hkulekci** [comment]
Arayüz Şablonu'da diyebiliriz belki.

**Comment by umutphp** [comment]
Kalıp Arapça şablon Almanca kökenli imiş :). Bana kalıp daha doğru geliyor. Kalıp diye düzeltip gönderdim.
