### ISSUE TITLE
Chang the Navigation

### ISSUE THREAD

**Issue by nhannqgh** [hkulekci/php-the-right-way#30]
How did you chang the Navigation?

**Comment by hkulekci** [comment]
I dont understand what you mean? Please, could you explain? @nhaancs

**Comment by nhannqgh** [comment]
@hkulekci I mean these stuff. I just wanna translate them to my language, but  cannot find any MD file for them. 

![untitled](https://cloud.githubusercontent.com/assets/15848072/15537210/3cd8da52-229f-11e6-83fc-32286cc13903.png)

**Comment by hkulekci** [comment]
this part is autogenerated part. They are created by a script which is https://github.com/hkulekci/php-the-right-way/blob/gh-pages/_layouts/default.html#L36

**Comment by hkulekci** [comment]
ping @nhaancs

**Comment by nhaancs** [comment]
@hkulekci so what  can I do bro?

**Comment by nhannqgh** [comment]
@hkulekci  so, what can I do bro?

**Comment by hkulekci** [comment]
The code use md files title parameter in this line https://github.com/hkulekci/php-the-right-way/blob/gh-pages/_layouts/default.html#L53 
The navigator will work if you change this title parameters.

**Comment by nhannqgh** [comment]
@hkulekci thank you :D

**Comment by hkulekci** [comment]
@nhaancs you are welcome 👍
